name: transactionmanager-integrationtests-sqlserver

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transactionmanager-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: Your_password123
    ports:
      - "1433:1433"
    volumes:
      - transactionmanager-sqlserver-data:/var/opt/mssql

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./schema.sql:/schema.sql:ro
      - ./init-sqlserver.sh:/init-sqlserver.sh:ro
    entrypoint: ["/bin/bash", "/init-sqlserver.sh"]

volumes:
  transactionmanager-sqlserver-data:
