name: transactionmanager-integrationtests-postgresql

services:
  postgresql:
    image: postgres:16
    container_name: transactionmanager-postgresql
    environment:
      POSTGRES_DB: txdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo1234
    ports:
      - "5432:5432"
    volumes:
      - transactionmanager-postgresql-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d txdemo"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  transactionmanager-postgresql-data:
