CREATE TABLE "Inventories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductName" character varying(200) NOT NULL,
    "Stock" integer NOT NULL,
    CONSTRAINT "PK_Inventories" PRIMARY KEY ("Id")
);


CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerName" character varying(200) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "Action" character varying(100) NOT NULL,
    "PerformedBy" character varying(200) NOT NULL,
    "PerformedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "ProductName" character varying(200) NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_AuditLogs_OrderId" ON "AuditLogs" ("OrderId");


CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");


